language: java
sudo: false

addons:
  apt:
    packages: &global_deps
      - ksh
      - bison
      - flex
      - gperf
      - libasound2-dev
      - libgl1-mesa-dev
      - libgstreamer0.10-dev
      - libgstreamer-plugins-base0.10-dev
      - libjpeg-dev
      - libpng-dev
      - libx11-dev
      - libxml2-dev
      - libxslt1-dev
      - libxt-dev
      - libxxf86vm-dev
      - pkg-config
      - libavcodec-dev
      - mercurial
      - libgtk2.0-dev
      - libgtk-3-dev
      - libxtst-dev
      - libudev-dev
      - libavformat-dev
      - cmake
      - ruby
      - gdb
      - libcups2-dev

# Won't be able to build webkit in the time alloted by Travis

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      install: . ./install-jdk.sh -F 10 -L GPL
      env: JDK='Open JDK 10'
      addons:
        apt:
          packages:
            - *global_deps
    - os: osx
      osx_image: xcode9
      # env: PRINT_CRASH_LOGS="true"

before_script:
  - echo $JAVA_OPTS
  - sh ./gradlew --version
  # run on xvfb screen (for linux).
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi

before_install: .ci/before_install.sh

# skip install stage.
install: true

script: .ci/script.sh

notifications:
  email: false

